### PR TITLE
feat: add cache option to renderTrpcPanel

### PR DESCRIPTION
**Pull request by pmenta**

### CODE REVIEW

**Comment by pmenta** [comment]
resolving the #42 issue

adding the option to disable the cache of RenderTRPCPanel, so everytime you refresh the page the routes will be updated

**Comment by iway1** [comment]
tysm! 😊

I may just go ahead and set the default to have it disable the cache, since it seems to be cause some confusion. I will create a release shortly

**Comment by iway1** [comment]
also going to set the cache to disabled by default I don't think it's worth the confusion it can cause

**Comment by iway1** [comment]
Released in 1.2.9

**Pull request merged**
